### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by frolf** [Heumi/Fast_Multi_Style_Transfer-tf#1]
Hello, I am just beginning to try to run your implementation. 

These are the steps I have taken so far:

-Created environment with requisite dependencies
-Cloned your github project
-Downloaded project files from your external link and extracted them to their proper directories.

When I try to first test with:

python main.py -f 0 -gn 0 -p MST \
  -tsd images/test \
  -scw 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0  \

I receive the following error:

major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:03:00.0
Total memory: 11.90GiB
Free memory: 10.50GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:03:00.0)
style_idx : 0
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 56, in main
    model.test(train_flag)
  File "/home/shannon/Desktop/multistyle/Fast_Multi_Style_Transfer-tf/src/multi_style_transfer.py", line 80, in test
    op.test(self,Train_flag)
  File "/home/shannon/Desktop/multistyle/Fast_Multi_Style_Transfer-tf/src/op.py", line 99, in test
    self.load()
  File "/home/shannon/Desktop/multistyle/Fast_Multi_Style_Transfer-tf/src/multi_style_transfer.py", line 86, in load
    op.load(self)
  File "/home/shannon/Desktop/multistyle/Fast_Multi_Style_Transfer-tf/src/op.py", line 133, in load
    ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

----

Any idea to resolve this issue?

Also, for training I already have the COCO Train2014 dataset on my machine.  When I go to train my own styles, where do I point your code towards my data folder containing Train2014?  And do you recommend using the 2015 Test dataset instead?

**Comment by hmi88** [comment]
I think model directory location occured this problem.
Did you download my models on your working directory? 
like "/home/shannon/Desktop/multistyle/Fast_Multi_Style_Transfer-tf/MST/models/"  
If you have still problem let me know, please 

and if you want use your COCO dataset, add this argument
        -ctd "COCO dataset folder"
        (example) -ctd /mnt/cloud/Data/COCO/train2014

I think you can use any dataset, val2014, test2014, test2015, and Imagenet. I used val2014+test2014

**Comment by frolf** [comment]
I was able to get it workking after creating a new directory. Between cloning your github and then downloading files from your storage, it can be easy to misplace the directory structure. Thank you for your help!

Also I believe in some of your example code in your readme you have only 15 arguments listed for -scw , when it is expecting 16.  Cheers!

**Comment by hmi88** [comment]
Thank you for interesting my project. This is my 1st implementation, so
there are lots of problem. If you find other problems, let me know it
please, and I'll fix it!

2017. 3. 14. 오전 4:36에 "frolf" <notifications@github.com>님이 작성:
