### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'src/vgg19.mat'

### ISSUE THREAD

**Issue by NZXGO** [Heumi/Fast_Multi_Style_Transfer-tf#2]
Excuse me, I have tried your code. Unfortunately, an error occurred, described  IOError: [Errno 2] No such file or directory: 'src/vgg19.mat'. Does Matlab need to be installed? Or, where is vgg19.mat?  Please help me solve it, please please

**Comment by hmi88** [comment]
No, you don't need Marla.  You can download vgg19.mat my onedrive link.

**Comment by NZXGO** [comment]
Thank you, I didn't see your instructions carefully.

**Comment by hmi88** [comment]
Thank you for your interesting! I'll upload more detail doc and model.

2017. 3. 13. 오후 6:09에 "NZXGO" <notifications@github.com>님이 작성:
