### ISSUE TITLE
Onedrive link can not be reached

### ISSUE THREAD

**Issue by xuguozhi** [Heumi/Fast_Multi_Style_Transfer-tf#3]
Hi，thank you for your work!  The project files can not be reached: https://1drv.ms/f/s!ArFpOdlDcjqQga8fwL0m4VQGmgKSfg
Can we get these files from other net disks? Such as BaiduYun(https://pan.baidu.com/) or Dropbox.
Thank you

**Comment by hmi88** [comment]
Sure! I'll upload to Dropbox before tommorow
